server:
  port: 8762

spring:
  application:
    name: finogram-gateway-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

# Disable accessing services using service name (i.e. gallery-service).
# They should be only accessed through the path defined below.
zuul:
  ignoredServices: "*"
  routes:
    finogramEngineService:
      path: /engine/**
      serviceId: finogram-engine-service